demokratie-live/bundestag.io

src/import.js

implemented the new scraperinterface,
some cleanups
-> dip21-scraper -> yarn build

implemented new scrape interface, cleanup

---

.travis.yml
package.json
yarn.lock

travis config

---

.gitignore
assets/templates/diff.html
package.json
src/import.js
yarn.lock

yarn link dip21-scraper
yarn imp

make changes for new scraper

---

.babelrc
.env
package.json
src/config/constants.js
src/config/db.js
src/index.js

- working azure settings
- excluded apollo
- fixed start command

Azure working

---

src/config/constants.js

doesnt work otherwise

---

.dockerignore
Dockerfile

Remaining questions:
- how to handle .env variables -> file vs commandline?
- which port to expose and how?

docker image

---

src/diffs.js
src/graphql/schemas/Document.graphql
src/graphql/schemas/Procedure.graphql
src/import.js
src/models/Procedure.js
src/models/Schemas/Document.js

documents und recourcen hinzugefügt

add missing fields

---

package.json
src/config/constants.js
src/graphql/resolvers/Procedure.js
src/importJob.js
src/index.js
src/models/CronJob.js
yarn.lock

Webhook hinzugefügt
**How to test**
Änderung an einer bestehenden Procedure machen
democracy server starten
`yarn dev`
in der log sollte min. ein update erscheinen

Webhook auslösen

---

.dockerignore

ignore more stuff in dockerignore

---

.travis.yml

docker build and push to dockerhub via travis

docker build and push to dockerhub via travis

---

.travis.yml
Dockerfile
src/importJob.js
src/index.js

try 2 fix docker container to run on azure

---

.gitignore
package.json
src/importJob.js
src/index.js
yarn.lock

add working status logging

---

Dockerfile

simplified docker instance - no more puppets

---

src/importJob.js

removed clearline & cursor(0) to work on docker properly
Merge and check on Azure

std out fix for docker

---

yarn.lock

updated dependencies to force rebuild
-> test on azure after merge

updated dependencies to force rebuild

---

Dockerfile

install lnav, output log

---

Dockerfile

removed lnav again - unnecessary

removed lnav

---

src/importJob.js

remove map error on when VORGANG has noch documents

fix map error

---

src/importJob.js
yarn.lock

5 browsers, updated scraper ref

---

.gitignore
Dockerfile
package.json
src/graphql/schemas/Decision.js
src/graphql/schemas/Document.js
src/graphql/schemas/Procedure.js
src/graphql/schemas/ProcessFlow.js
src/graphql/schemas/Schema.graphql
src/graphql/schemas/Schema.js

```
yarn build
yarn serve
```
startet der server?
https://github.com/demokratie-live/democracy-development/pull/6

Sprint#6/babel build

---

Dockerfile
package.json

install yarn

---

src/graphql/resolvers/Procedure.js
src/graphql/schemas/Procedure.js

fix import all on wrong procedure number

sprint#7 Push Notification

---

src/graphql/resolvers/Procedure.js

webhook when updating bundestagresults

---

yarn.lock

updated scraper ref to 0.1.2

---

CHANGELOG.md
package.json
src/config/constants.js
src/importJob.js
src/index.js
src/models/Procedure.js
src/models/Schemas/PartyVotes.js
src/models/Schemas/ProcessFlow.js
yarn.lock

https://github.com/demokratie-live/democracy-development/pull/119

sprint#16/suche

---

CHANGELOG.md
Dockerfile
package.json
src/config/constants.js
src/config/db.js
src/diffs.js
src/graphql/schemas/Procedure.js
src/importAgenda.js
src/index.js
src/models/Agenda.js
src/models/Procedure.js
yarn.lock

https://github.com/demokratie-live/democracy-development/pull/121

sprint#16/bt-agenda

---

package.json
src/importJob.js
src/index.js
yarn.lock

add html scraper
https://github.com/demokratie-live/democracy-development/pull/126

sprint#17/html scraper

---

CHANGELOG.md
src/graphql/resolvers/Procedure.js
src/graphql/schemas/Procedure.js

https://github.com/demokratie-live/democracy-development/pull/127

sprint#17/currentStatus-history

---

src/graphql/resolvers/Procedure.js

fix import webhook timeout
https://github.com/demokratie-live/democracy-development/pull/142

sprint#19/fix import webooks timeout

---

src/graphql/resolvers/Procedure.js

https://github.com/demokratie-live/democracy-development/pull/74

sprint#11/push-notifications#2

---

CHANGELOG.md
components/admin/Procedure.jsx
components/admin/VoteEdit.jsx
package.json
src/graphql/resolvers/Procedure.js
src/graphql/schemas/Procedure.js

https://github.com/demokratie-live/democracy-development/pull/150

sprint#22/not named vote results

---

CHANGELOG.md
src/importJob.js

Sprint#36/fix update push messages

---

CHANGELOG.md
src/graphql/schemaDirectives/auth.js

Sprint#37/fix server whitelisting

---

CHANGELOG.md
src/config/db.js
src/diffs.js
src/importJob.js
src/index.js

Try Catch all errors and die on them.
Todo:

Sprint#35/try catch

---

CHANGELOG.md
package.json
src/graphql/resolvers/Procedure.js

Add missing procedures in admin area

sprint#41/admin-missing-procedures

---

src/graphql/resolvers/Procedure.js
src/graphql/schemas/Procedure.js
src/importAgenda.js
src/models/Procedure.js
yarn.lock

Sprint#41/procedure list status fix
